### PR TITLE
Fix error raised in Keyboard.parse when $log is nil

### PR DESCRIPTION
**Pull request by Phitherek**

### CODE REVIEW

**Comment by Phitherek** [comment]
Fixes #1

**Comment by acook** [comment]
Hey @Phitherek thanks for the PR, I'll merge to give you credit for the contribution but it turns out this line actually should just be removed. 

BTW the website listed on your Github profile appears to be broken, you might want to take a look.

Thanks for submitting a fix!

**Comment by Phitherek** [comment]
@acook Thanks for the merge! I didn't want to remove any code since I didn't know your intention, so I did it in the non-invasive way. And yes, I need to develop a new website for myself, because the old one appears to have expired. It was old and not good anyways ;).

By the way, awesome gem, the keyboard interaction part really helps me out in my project. I would also encourage you to take look at the (not mine, but still awesome) TTY gem, I am also using it, this is a multi-platform console framework similar to Curses but written in a pure Ruby, it may help you out with your gem. I hope that you continue on with the development :).

**Comment by acook** [comment]
Thanks! I'm glad you've found it useful.

Remedy is highly modular and should work fine with TTY, you should even be able to embed TTY tables inside Remedy Viewports without any trouble, and the Viewport will automatically fit the data to the screen and use `Console.set_console_resized_hook!` to redraw the tables when the user resizes their terminal.

**Comment by Phitherek** [comment]
@acook Nice! I hope this gem matures nicely then :)

**Pull request merged**
